tap "microsoft/mssql-release", "https://github.com/Microsoft/homebrew-mssql-release"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Quickly rewrite git repository history
brew "git-filter-repo"
# Java-based project management
brew "maven"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Development kit for the Java programming language
brew "openjdk@21"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Python package management tool
brew "poetry"
# Cross-platform library for audio I/O
brew "portaudio"
# Interpreted, interactive, object-oriented programming language
brew "python@3.13"
# ODBC 3 connectivity for UNIX
brew "unixodbc"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# ODBC Driver for Microsoft(R) SQL Server(R)
brew "microsoft/mssql-release/msodbcsql18", trusted: true
# Terminal-based AI coding assistant
cask "claude-code@latest"
# Universal database tool and SQL client
cask "dbeaver-community"
# Online diagram software
cask "drawio"
cask "font-comic-mono"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Replacement for Docker Desktop
cask "orbstack"
